var elements = document.getElementsByTagName('*');

var sourceWordsToTargetWords = [

    //faces and emotions
    [['happy'], '😀'],
    [['haha', 'lol', 'lmao', 'rofl'], '😂'],
    [['oops'], '😅'],
    [['skeptical'], '🤨'],
    [['thinking'], '🤔'],
    [['speechless'], '😶'],
    [['lips are sealed', 'keep a secret'], '🤐'],
    [['annoyed'], '🙄'],
    [['shocked', 'surprised'], '😮'],
    [['sleeping'], '😴'],
    [['idk', 'uncertain'], '😕'],
    [['sad'], '😢'],
    [['greedy', 'greed'], '🤑'],
    [['weeping'], '😭'],
    [['angry'], '😡'],
    [['evil'], '😈'],
    [['alien'], '👽'],
    [['skull'], '💀'],
    [['ghost'], '👻'],
    [['poop', 'crap', 'turd'], '💩'],
    [['robot'], '🤖'],
    [['nerd'], '🤓 '],
    [['sick'], '🤒'],
    [['innocent', 'angel'], '😇'],
    [['injured'], '🤕'],
    [['awkward', 'uncomfortable', 'yikes'], '😬'],
    [['crazy'], '🤪'],
    [['scared'], '😨'],
    [['fuck', 'shit'], '🤬'],

    //body, clothing, and accessories
    [['eyes'], '👀'],
    [['brain'], '🧠'],
    [['eye'], '👁'],
    [['shirt'], '👕'],
    [['jeans', 'pants'], '👖'],
    [['dress'], '👗'],
    [['bikini'], '👙'],
    [['sunglasses'], '🕶'],
    [['crown'], '👑'],
    [['backpack'], '🎒'],
    [['umbrella'], '🌂'],

    //animals and nature
    [['dog', 'puppy', 'canine'], '🐶'],
    [['cat', 'kitten', 'kitty'], '🐱'],
    [['mouse'], '🐭'],
    [['rabbit', 'bunny'], '🐰'],
    [['panda bear', 'panda'], '🐼'],
    [['bear'], '🐻'],
    [['tiger'], '🐯'],
    [['lion'], '🦁'],
    [['cow'], '🐮'],
    [['pig'], '🐷'],
    [['frog'], '🐸'],
    [['monkey'], '🐵'],
    [['fox'], '🦊'],
    [['koala'], '🐨'],
    [['chicken', 'hen'], '🐔'],
    [['penguin'], '🐧'],
    [['pigeon'], '🐦'],
    [['chick'], '🐥'],
    [['duck'], '🦆'],
    [['eagle'], '🦅'],
    [['owl'], '🦉'],
    [['bat'], '🦇'],
    [['wolf'], '🐺'],
    [['horse'], '🐴'],
    [['unicorn'], '🦄'],
    [['bee'], '🐝'],
    [['bug'], '🐛'],
    [['butterfly'], '🦋'],
    [['beetle'], '🐞'],
    [['ant'], '🐜'],
    [['cricket'], '🦗'],
    [['spider'], '🕷'],
    [['spiderweb'], '🕸'],
    [['scorpion'], '🦂'],
    [['turtle'], '🐢'],
    [['snake'], '🐍'],
    [['lizard'], '🦎'],
    [['trex'], '🦖'],
    [['dinosaur', 'dino'], '🦕'],
    [['dragon'], '🐉'],
    [['octopus'], '🐙'],
    [['squid'], '🦑'],
    [['shrimp', 'prawn'], '🦐'],
    [['crab'], '🦀'],
    [['fish'], '🐟'],
    [['dolphin'], '🐬'],
    [['whale'], '🐳'],
    [['shark'], '🦈'],
    [['cactus'], '🌵'],
    [['christmas tree'], '🎄'],
    [['pine tree'], '🌲'],
    [['Palm tree', 'palm tree', 'Palm trees', 'Palm Tree'], '🌴'],
    [['tree'], '🌳'],
    [['plant'], '🌱'],
    [['clover', 'lucky'], '☘️'],
    [['leaves'], '🍃'],
    [['maple'], '🍁'],
    [['mushroom'], '🍄'],
    [['wheat'], '🌾'],
    [['rose'], '🌹'],
    [['tulip'], '🌷'],
    [['sunflower'], '🌻'],
    [['sun', 'sunny', 'Sun'], '☀️'],
    [['star'], '⭐️'],
    [['world', 'Earth', 'earth'], '🌎'],
    [['moon'], '🌕'],
    [['crescent'], '🌙'],
    [['fire'], '🔥'],
    [['rainbow'], '🌈'],
    [['tornado'], '🌪'],
    [['cloud', 'cloudy'], '☁️'],
    [['rain', 'raining'], '🌧'],
    [['storm', 'thunderstorm'], '⛈'],
    [['lightning'], '🌩'],
    [['snow'], '🌨'],
    [['snowflake'], '❄️'],
    [['water'], '💦'],
    [['snowman'], '⛄️'],
    [['wind'], '💨'],
    [['explosion', 'boom', 'bam'], '💥'],
    [['shock'], '⚡️'],
    [['sparkles', 'sparkling', 'sparkle'], '✨'],

    //food and drink
    [['apple'], '🍎'],
    [['pear'],'🍐'],
    [['orange','tangerine'],'🍊'],
    [['banana'],'🍌'],
    [['watermelon'],'🍉'],
    [['grape'],'🍇'],
    [['strawberry'],'🍓'],
    [['melon'],'🍈'],
    [['cherry'],'🍒'],
    [['peach'],'🍑'],
    [['pineapple'],'🍍'],
    [['coconut'],'🥥'],
    [['kiwi'],'🥝'],
    [['tomato'],'🍅'],
    [['eggplant'],'🍆'],
    [['avocado'],'🥑'],
    [['brocoli'],'🥦'],
    [['cucumber'],'🥒'],
    [['pepper'],'🌶'],
    [['corn'],'🌽'],
    [['carrot'],'🥕'],
    [['potato'],'🥔'],
    [['sweet potato'],'🍠'],
    [['croissant'],'🥐'],
    [['bread'],'🍞'],
    [['baguette'],'🥖'],
    [['pretzel'],'🥨'],
    [['cheese'], '🧀'],
    [['egg'], '🥚'],
    [['eggs'], '🍳'],
    [['pasta'], '🍝'],
    [['pancake', 'pancakes'], '🥞'],
    [['bacon'], '🥓'],
    [['steak', 'meat'], '🥩 '],
    [['chicken drumstick', 'chicken leg'], '🍗'],
    [['pork'], '🍖'],
    [['hot dog'], '🌭'],
    [['hamburger'], '🍔'],
    [['french fries'], '🍟'],
    [['pizza'], '🍕'],
    [['sandwich'], '🥪'],
    [['pita wrap'], '🥙'],
    [['taco'], '🌮'],
    [['burrito'], '🌯'],
    [['salad'], '🥗'],
    [['slice of cake'], '🍰'],
    [['cake'], '🎂'],
    [['rice'], '🍚'],
    [['beer', 'alcohol'], '🍺'],
    [['beers'], '🍻'],
    [['donut'], '🍩 '],
    [['cookie'], '🍪'],
    [['peanut'], '🥜'],
    [['milk'], '🥛'],
    [['honey'], '🍯'],
    [['coffee'], '☕️'],
    [['martini'], '🍸'],
    [['spoon'], '🥄'],
    [['fork and knife'], '🍴'],
    [['soda'], '🥤'],
    [['popcorn'], '🍿'],
    [['pie'], '🥧'],
    [['chocolate'], '🍫'],
    [['candy'], '🍬'],
    [['lollipop'], '🍭'],

    //activity and sports
    [['first'], '🥇'],
    [['second'], '🥈'],
    [['third'], '🥉'],
    [['soccer'], '⚽️'],
    [['basketball'], '🏀'],
    [['football'], '🏈'],
    [['baseball'], '⚾️'],
    [['volleyball'], '🏐'],
    [['rugby'], '🏉'],
    [['table tennis', 'Table Tennis', 'Table tennis', 'ping pong'], '🏓'],
    [['tennis'], '🎾'],
    [['pool'], '🎱'],
    [['badminton'], '🏸 '],
    [['golf'], '⛳️'],
    [['ice skate'], '⛸'],
    [['boxing'], '🥊'],
    [['sled'], '🛷'],
    [['ticket'], '🎟'],
    [['concert'], '🎫'],
    [['champion'], '🏆'],
    [['fishing'], '🎣'],
    [['art'], '🎨'],
    [['theatre', 'theater', 'drama', 'performing arts'], '🎭'],
    [['drums', 'drum'], '🥁'],
    [['piano', 'keyboard'], '🎹'],
    [['microphone'], '🎤'],
    [['headphones'], '🎧'],
    [['violin'], '🎻'],
    [['die'], '🎲'],
    [['saxophone'], '🎷'],
    [['trumpet'], '🎷'],
    [['guitar'], '🎸'],
    [['bowling'], '🎳'],
    [['gaming'], '🎮'],
    [['gambling'], '🎰'],

    //travel and places
    [['car'], '🚗'],
    [['taxi'], '🚕'],
    [['bus'], '🚌'],
    [['police car'], '🚓'],
    [['police'], '🚔'],
    [['fire truck', 'fire engine'], '🚒'],
    [['ambulance'], '🚐'],
    [['scooter'], '🛴'],
    [['bicycle'], '🚲'],
    [['monorail'], '🚝'],
    [['train'], '🚂'],
    [['airplane'], '✈️'],
    [['helicopter'], '🚁'],
    [['ufo', 'UFO'], '🛸'],
    [['sailboat'], '⛵️'],
    [['rocket'], '🚀 '],
    [['ship'], '🚢'],
    [['castle'], '🏰'],
    [['anchor'], '⚓️'],
    [['satellite'], '🛰'],
    [['traffic light'], '🚦'],
    [['beach'], '🏖'],
    [['ferris wheel'], '🎡'],
    [['volcano'], '🌋'],
    [['mountain'], '⛰'],
    [['home', 'house'], '🏠'],
    [['fountain'], '⛲️'],
    [['tent'], '⛺️'],
    [['factory'], '🏭'],
    [['church'], '⛪️'],
    [['bank'], '🏦'],
    [['hospital'], '🏨'],
    [['stadium'], '🏟'],
    [['mosque'], '🕌'],
    [['synagogue'], '🕍'],
    [['motorcycle'], '🏍'],
    [['city'], '🏙'],
    [['map'], '🗺'],
    [['construction'], '🚧'],
    [['gasoline'], '⛽️'],

    //objects
    [['watch'], '⌚️'],
    [['smartphone'], '📱'],
    [['laptop'], '💻'],
    [['desktop'], '🖥'],
    [['printer'], '🖨'],
    [['camera'], '📷'],
    [['cd'], '💿'],
    [['dvd'], '📀'],
    [['film'], '🎞'],
    [['telephone'], '☎️'],
    [['call'], '📞'],
    [['television', 'tv', 'TV'], '📺'],
    [['stopwatch'], '⏱'],
    [['timer'], '⏲'],
    [['alarm clock'], '⏰'],
    [['hourglass'], '⏳'],
    [['battery', 'power'], '🔋'],
    [['light bulb'], '💡'],
    [['candle'], '🕯'],
    [['law', 'justice'], '⚖️'],
    [['trash can', 'trash bin', 'rubbish bin'], '🗑'],
    [['dollars', 'cash'], '💵'],
    [['money'], '💰'],
    [['gem', 'diamond'], '💎'],
    [['wrench'], '🔧'],
    [['hammer'], '🔨'],
    [['tools'], '🛠'],
    [['gear'], '⚙️'],
    [['chain'], '⛓'],
    [['bomb'], '💣'],
    [['gun'], '🔫'],
    [['knife'], '🔪'],
    [['sword'], '🗡'],
    [['shield'], '🛡'],
    [['pill'], '💊'],
    [['microscope', 'science', 'technology', 'tech'], '🔬'],
    [['telescope', 'astronomy'], '🔭'],
    [['key'], '🔑'],
    [['balloon'], '🎈'],
    [['gift'], '🎁'],
    [['shopping cart'], '🛒'],
    [['mail'], '✉️'],
    [['picture'], '🖼'],
    [['email'], '📧'],
    [['box'], '📦'],
    [['calendar'], '🗓'],
    [['pencil'], '✏️'],
    [['lock'], '🔒'],
    [['pin'], '📍'],
    [['notebook'], '📓'],
    [['newspaper'], '📰'],
    [['books'], '📚'],
    [['book'], '📖'],
    [['search'], '🔎'],
    [['celebration', 'celebrate'], '🎉'],
    [['data'], '📊'],
    [['cut', 'scissors'], '✂️ '],
    [['trends', 'trend'], '📈'],
    [['entertainment', 'movies', 'movie'], '🎬'],
    [['health', 'syringe'], '💉'],

    //symbols
    [['heart', 'love'], '❤️'],
    [['heartbroken'], '💔'],
    [['valentine'], '💘'],
    [['death'], ''],
    [['exclamation mark'], '❗️'],
    [['question'], '❓'],
    [['caution', 'alert'], '⚠️'],
    [['replay'], '🔁'],
    [['music'], '🎵'],
    [['USA', 'US', 'United States of America', 'United States'], '🇺🇸'],
    [['lgbqt', 'LGBQT'], '🏳️‍🌈'],
    [['recycle', 'sustainability'], '♻️'],
    [['peace'], '☮️'],
    [['ban'], '🚫'],
    [['time'], '🕓'],
];

function makeRegex(sourceWords) {
    return new RegExp('\\b' + sourceWords.join('\\b|\\b') + '\\b', 'g');
};

function identity(string) {
    return string;
};

function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
};

function toUpperCase(string) {
    return string.toUpperCase();
};

function makeRegexToTargetWords(sourceWordsToTargetWords, modifyWords) {
    return sourceWordsToTargetWords.map(function(sourceAndTarget) {
        var [source,target] = sourceAndTarget;
        source = source.map(modifyWords);
        target = modifyWords(target);
        return [makeRegex(source), target];
    });
};

var sourceRegexToTargetWords = makeRegexToTargetWords(sourceWordsToTargetWords, identity).concat(makeRegexToTargetWords(sourceWordsToTargetWords, capitalizeFirstLetter)).concat(makeRegexToTargetWords(sourceWordsToTargetWords, toUpperCase));

function replaceTextWithRegexes(text, sourceRegexToTargetWords) {
    for (var k = 0; k < sourceRegexToTargetWords.length; k++) {
        var [regex, targetWord] = sourceRegexToTargetWords[k];
        var replacedText = text.replace(regex, targetWord);
        text = replacedText
    }
    return text;
};

for (var i = 0; i < elements.length; i++) {
    var element = elements[i];

    for (var j = 0; j < element.childNodes.length; j++) {
        var node = element.childNodes[j];

        if (node.nodeType === 3) {
            var text = node.nodeValue;
            replacedText = replaceTextWithRegexes(text, sourceRegexToTargetWords);

            if (replacedText !== text) {
                console.log('replaced');
                element.replaceChild(document.createTextNode(replacedText), node);
            }
        }
    }
}
